GET /api/degreetodms?lat=37.55369139&long=128.2131775 HTTP/2
Host: coordtrans.appspot.com

###

GET /api/dmstodegree?lat_degree=37&lat_arcminute=33&lat_arcsecond=13.289&long_degree=128&long_arcminute=12&long_arcsecond=47.439 HTTP/2
Host: coordtrans.appspot.com
